name: flutter_base_example
description: Demonstrates how to use the flutter_base plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_base:
    # When depending on this package from a real application you should use:
    #   flutter_base: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version. 
    path: ../

  flutter_bugly: ^0.2.8
  #  flutter_base:
  #    git:
  #      url: https://github.com/Li-Zepeng/flutter_base.git
  #      ref: master

  #  video_player: ^0.10.11+1 # 视频播放 https://github.com/flutter/plugins/tree/master/packages/video_player
  #  flare_flutter: ^2.0.3 # 动画效果 https://github.com/2d-inc/Flare-Flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  web: true
  image_path: "assets/images/ic_launcher.png"
#  adaptive_icon_background: "#FF64B5F6"
#  adaptive_icon_foreground: "assets/images/ic_launcher_foreground.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png
  # android_disable_fullscreen: true # 禁用android全屏启动
  fill: true # android下占满

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Gotham-Book
      fonts:
        - asset: fonts/Gotham-Book.otf
        - asset: fonts/Gotham-Book.otf
          style: italic
        - asset: fonts/Gotham-Book.otf
          weight: 700

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
